# Generated by Django 4.2.11 on 2024-05-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("tid", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                ("pid", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("file_path", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.sakanauser",
                    ),
                ),
                ("tags", models.ManyToManyField(to="core.tag")),
            ],
            options={"ordering": ["title"],},
        ),
    ]
