# Generated by Django 4.2.11 on 2024-05-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                ("wid", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="Untitled Workflow", max_length=100)),
                ("work_type", models.IntegerField()),
                ("instructions", models.TextField()),
                ("stage", models.CharField(max_length=50)),
                ("status", models.IntegerField()),
                ("messages", models.TextField()),
                ("result", models.TextField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.paper"
                    ),
                ),
                (
                    "starter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.sakanauser",
                    ),
                ),
            ],
            options={"ordering": ["-last_updated"],},
        ),
    ]
