# Generated by Django 4.2.11 on 2024-05-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow", name="status", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="work_type",
            field=models.CharField(max_length=50),
        ),
    ]
