# work_type
UPLOAD = 0
PROCESS = 1
UPLOAD_AND_PROCESS = "upload_process"
OTHER = 2

# status
PENDING = 0
TAGS_READY = "tags ready"
COMPLETED = 1
FAILED = 2
ABORTED = 3

# stage
S_START = 0
S_UPLOAD_AND_PROCESS = "upload and process"
S_UPLOADING = 1
S_PROCESSING_0 = 2
S_PROCESSING_1 = 3
S_PROCESSING_2 = 4
S_POST_PROCESS = "post-process"
S_END = 5

# incompatible work type
INCOMPATIBLE_WORK_TYPE = [UPLOAD_AND_PROCESS, UPLOAD, PROCESS]

# statuses - end polling
END_POLLING_STATUS = [COMPLETED, FAILED, ABORTED, TAGS_READY]

# statuses - can abort
CAN_ABORT_STATUS = [PENDING, TAGS_READY]
