name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./SakanaRM --file Dockerfile.prod --tag sakanarm:version1.0
    - name: Run image
      run: docker run -d sakanarm:version1.0
    - name: Run tests
      run: docker exec -it sakanarm:version1.0 python manage.py test
